### ISSUE TITLE
Error with WMS-T layer

### ISSUE THREAD

**Issue by samtux** [anitagraser/TimeManager#149]
I get the next error with WMS-T layer:

http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r-t.cgi?LAYERS=nexrad-n0r-wmst&TRANSPARENT=TRUE&FORMAT=image/png&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&SRS=EPSG:4326&BBOX=-126,24,-66,50&WIDTH=600&HEIGHT=500&TIME=2015-10-20T00:00:00Z/2015-10-24T00:00:00

```python
Ha ocurrido un error mientras se ejecutaba el código de Python:

Traceback (most recent call last):
  File "/home/samtux/.qgis2/python/plugins/timemanager/timemanagercontrol.py", line 308, in playAnimation
    haveVisibleFeatures = self.timeLayerManager.haveVisibleFeatures()
  File "/home/samtux/.qgis2/python/plugins/timemanager/timelayermanager.py", line 283, in haveVisibleFeatures
    total_features += layer.featureCount()
AttributeError: 'QgsRasterLayer' object has no attribute 'featureCount'

Versión de Python:
2.7.10 (default, Sep  7 2015, 13:51:49) 
[GCC 5.2.0]

Versión de QGIS:
2.10.1-Pisa Pisa, eaf06be

Ruta de Python: ['/home/samtux/.qgis2/python/plugins/processing', '/home/samtux/.qgis2/python/plugins/processing_workflow', '/home/samtux/.qgis2/python/plugins/esstoolkit/external', '/usr/share/qgis/python', u'/home/samtux/.qgis2/python', u'/home/samtux/.qgis2/python/plugins', '/usr/share/qgis/python/plugins', '/opt/grass/etc/python', '/home/samtux', '/usr/lib/python27.zip', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-linux2', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/lib/python2.7/site-packages', '/usr/lib/python2.7/site-packages/gst-0.10', '/usr/lib/python2.7/site-packages/gtk-2.0', '/usr/lib/python2.7/site-packages/wx-3.0-gtk2', u'/home/samtux/.qgis2//python', '.', '/home/samtux/.qgis2/python/plugins/OpenAerialMap', '/home/samtux/.qgis2/python/plugins/OpenAerialMap/ext_libs/boto-2.38.0', '/home/samtux/.qgis2/python/plugins/OpenAerialMap/ext_libs/filechunkio-1.6', '/home/samtux/.qgis2/python/plugins/OpenAerialMap/ext_libs/requests-2.7.0', '/usr/share/qgis/python/plugins/fTools/tools']
```

**Comment by carolinux** [comment]
Fixed at commit: 2ffcd4c369d937f 
Please use the latest version from github
Let me know if it works for you

**Comment by samtux** [comment]
@carolinux the error persists, I believe that it is necessary to define a conditional to identify the layer raster line 283 of timelayermanager.py, this would be like:

```python
if self.getActiveRasters () is False:
    for layer in all_layers:
        total_features += layer.featureCount)
```
Although I do not know if this change affects the animation of vector layers.

Here the output of the animation using this great tool.

![Timemanager](http://i.imgur.com/NxHKDUR.gif)

**Comment by carolinux** [comment]
it should work in c256f5d
I wasnt checking if the layer is a raster layer properly in the initial fix
