### ISSUE TITLE
Problem with Archaeology Mode

### ISSUE THREAD

**Issue by dbobak** [anitagraser/TimeManager#262]
In short - Archaeology Mode does not work. I have the following fields in my layer: from_bc and to_bc, all 5 digits. So the data is in format: "10459 BC", "0975 BC" and so on.
1. I'm turning on Archaeology mode and setting the number of digits to 5.
2. Adding the layer in Time manager settings dialog, choosing the appropriate fields for start and end time
3. After closing the dialog, nothing happens
4. After opening the settings dialog again, the added layer is not present on the list.

I'm attaching the layer in shp format.
[dates.zip](https://github.com/anitagraser/TimeManager/files/2516170/dates.zip)

Versions: 
Time manager: 3.0.1
QGIS: 3.2.3 installed from OSGEO4W network installer (also tried with the last nightly build, the problem is the same)
OS: Windows 10 Professional

**Comment by carolinux** [comment]
I might take a look at this. It might be related to something I discovered regarding the 'archaelogy setting=ON' not persisting.

**Comment by carolinux** [comment]
@dbobak You can try using the current master of the repo and see if it fixes your problem (see [here](https://github.com/anitagraser/TimeManager/blob/master/docs/GITHUB.md) how to use the current master. 

I fixed the way I'm persisting the archaeology setting.

**Comment by dbobak** [comment]
Sorry for the late response, @carolinux. I've tested the current mater version and there are problems still.  On loading the project with time manager options enabled, or when trying to change time manager options, I'm getting the following error:

```
An error has occurred while executing Python code: 

TypeError: can't multiply sequence by non-int of type 'str' 
Traceback (most recent call last):
  File "C:/Users/deni/AppData/Roaming/QGIS/QGIS3\profiles\deni/python/plugins\timemanager\timemanagercontrol.py", line 608, in readSettings
    restore_function(setting_value)
  File "C:/Users/deni/AppData/Roaming/QGIS/QGIS3\profiles\deni/python/plugins\timemanager\timemanagercontrol.py", line 454, in setArchaeology
    "Y" * time_util.getArchDigits()
TypeError: can't multiply sequence by non-int of type 'str'


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.6.1-Noosa Noosa, 2468226bc9 

Python Path:
C:/OSGEO4~1/apps/qgis/./python
C:/Users/deni/AppData/Roaming/QGIS/QGIS3\profiles\deni/python
C:/Users/deni/AppData/Roaming/QGIS/QGIS3\profiles\deni/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\Users\deni\AppData\Roaming\Python\Python37\site-packages
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/deni/AppData/Roaming/QGIS/QGIS3\profiles\deni/python
C:\Users\deni\AppData\Roaming\QGIS\QGIS3\profiles\deni\python\plugins\mmqgis/forms
.
C:/Users/deni/Documents/archeo/projekty/@works/publikacje/@w_trakcie/Dawn-of-the-mesolithic
```

**Comment by carolinux** [comment]
hi @dbobak, I think this is a different problem than before. Pushed a quick fix for it to master.

**Comment by dbobak** [comment]
hi @carolinux. the problem still exists:

```
2019-04-05T11:53:21     WARNING    Traceback (most recent call last):
              File "C:/Users/deni/AppData/Roaming/QGIS/QGIS3\profiles\deni/python/plugins\timemanager\utils\bcdate_util.py", line 90, in from_str
              year_str = m.group(1)
             AttributeError: 'NoneType' object has no attribute 'group'
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:/Users/deni/AppData/Roaming/QGIS/QGIS3\profiles\deni/python/plugins\timemanager\utils\time_util.py", line 334, in str_to_datetime
              return bcdate_util.str_to_bcdate(datetimeString)
              File "C:/Users/deni/AppData/Roaming/QGIS/QGIS3\profiles\deni/python/plugins\timemanager\utils\bcdate_util.py", line 213, in str_to_bcdate
              return BCDate.from_str(datetimeString)
              File "C:/Users/deni/AppData/Roaming/QGIS/QGIS3\profiles\deni/python/plugins\timemanager\utils\bcdate_util.py", line 110, in from_str
              "1".zfill(getGlobalDigitSetting())))
             Exception: None is an invalid archaelogical date, should be 'number AD' or 'number BC'and year 0 (use 0001 AD or BC instead) doesn't exist.
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:/Users/deni/AppData/Roaming/QGIS/QGIS3\profiles\deni/python/plugins\timemanager\timemanagercontrol.py", line 608, in readSettings
              restore_function(setting_value)
              File "C:/Users/deni/AppData/Roaming/QGIS/QGIS3\profiles\deni/python/plugins\timemanager\timemanagercontrol.py", line 622, in restoreTimePositionFromSettings
              dt = time_util.str_to_datetime(value, time_util.DEFAULT_FORMAT) # this also works for integer values
              File "C:/Users/deni/AppData/Roaming/QGIS/QGIS3\profiles\deni/python/plugins\timemanager\utils\time_util.py", line 344, in str_to_datetime
              createNiceMessage(datetimeString, specified_fmt, is_archaelogical(), e))
             timemanager.utils.time_util.UnsupportedFormatException: Data with value None is not a valid archaelogical format. Cause: None is an invalid archaelogical date, should be 'number AD' or 'number BC'and year 0 (use 0001 AD or BC instead) doesn't exist.If you are trying to use a regular date, please disable archaelogical mode by clicking on thebutton next to Settings
```

**Comment by carolinux** [comment]
Can you give me the dataset you are trying to load, please? Also, since the
error is different, it is a different problem further down the line -
progress is being made. The issues have to do with the migration to
python3. Email me at carolinegr@gmail.com with the files.
